version: '3'

services:
  certbot:
    container_name: certbot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./lib:/var/lib/letsencrypt
    #entrypoint: >
    #  sh -c 'trap exit TERM; while :; do
    #           certbot renew \
    #             --dns-cloudflare \
    #             --dns-cloudflare-credentials /secrets/cloudflare.ini \
    #             --dns-cloudflare-propagation-seconds 30;
    #           sleep 7d & wait $${!};
    #         done;'
    entrypoint: >
      sh -c 'trap exit TERM; while :; do
               certbot renew;
               sleep 12h & wait $${!};
             done;'
